### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by jessearmstrong** [yesthisisjoe/Wallpaperer-releases#1]
Wallpaperer instantly crashes upon launch for me. I can see the icon enter then immediately leave the menu bar upon launch.

**Comment by Spartacode** [comment]
I am also getting this. Is the app pulled now? Not seeing it from GitHub at all.

**Comment by yesthisisjoe** [comment]
The app should be available under Releases.

As for the crash, I'm looking into it!

**Comment by liudayu** [comment]
@yesthisisjoe Any updates? It's crashing on my MacBook Pro 15, mid - 2015, but strangely, not on my MacBook Pro 13, mid - 2014.

**Comment by yesthisisjoe** [comment]
I'll try to get this fixed soon. In the meantime deleting your preferences from the command line should fix it.

Try:
defaults delete com.yesthisisjoe.Wallpaperer

**Comment by jessearmstrong** [comment]
Huzzah that worked! Thank you!

**Comment by Spartacode** [comment]
This is really weird. I had stopped using it a while ago because of the instant crash on it. Well it just started to work one day. I logged in and my wallpaper was updating again and app was open.  Thanks for the awesome app. Please keep it up. I love a new wallpaper every so often. 

Jerry

**Comment by goodwind** [comment]
any updates? judging by logs, error is the same that was in 4.0

4.0
> Crashing on exception: NSLayoutConstraint constant is not finite!  That's illegal.  constant:nan firstAnchor:<NSLayoutDimension:0x604000661c00 "Wallpaperer.ThumbnailImageView:0x604000197eb0.width"> secondAnchor:(null)

5.0
>Crashing on exception: NSLayoutConstraint constant is not finite!  That's illegal.  constant:nan firstAnchor:<NSLayoutDimension:0x60400067e780 "Wallpaperer.ThumbnailImageView:0x604000380410.width"> secondAnchor:(null)

**Comment by lycrake** [comment]
Hey there, did this ever get sorted? Still seems to happen, Sierra 10.12.6

**Comment by jessearmstrong** [comment]
This has been fully resolved for me, I did have to run this terminal command before it worked though. 

defaults delete com.yesthisisjoe.Wallpaperer

I use it every day on multiple machines.

**Comment by lycrake** [comment]
Weird, I still get the below after running the command

Application Specific Information:
Crashing on exception: NSLayoutConstraint constant is not finite!  That's illegal.  constant:nan firstAnchor:<NSLayoutDimension:0x608000270540 "Wallpaperer.ThumbnailImageView:0x60800019de90.width"> secondAnchor:(null)

I'll do some digging to see what else the problem could be on my end

**Comment by yesthisisjoe** [comment]
Marking as closed. If anyone sees this again, please let me know.
